package com.trial.bsat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BSAT_Module implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String status;

	private java.lang.String res_line_status;

	private java.lang.Integer so_line_total;

	public BSAT_Module() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getRes_line_status() {
		return this.res_line_status;
	}

	public void setRes_line_status(java.lang.String res_line_status) {
		this.res_line_status = res_line_status;
	}

	public java.lang.Integer getSo_line_total() {
		return this.so_line_total;
	}

	public void setSo_line_total(java.lang.Integer so_line_total) {
		this.so_line_total = so_line_total;
	}

	public BSAT_Module(java.lang.String status,
			java.lang.String res_line_status, java.lang.Integer so_line_total) {
		this.status = status;
		this.res_line_status = res_line_status;
		this.so_line_total = so_line_total;
	}

}